### ISSUE TITLE
Support httpapi in reosurce modules

### ISSUE THREAD

**Issue by Qalthos** [ansible-collections/cisco.nxos#19]
##### SUMMARY

- [x] Add support to httpapi plugin (#17)
- [x] Migrate tests to cover both connections:
  - [x] nxos_acls (#38)
  - [x] nxos_acl_interfaces (#38)
  - [x] nxos_bfd_interfaces (#38)
  - [x] nxos_interfaces (#17)
  - [x] nxos_l2_interfaces (#24)
  - [x] nxos_l3_interfaces (#24)
  - [x] nxos_lacp (#24)
  - [x] nxos_lacp_interfaces (#24)
  - [x] nxos_lag_interfaces (#38)
  - [x] nxos_lldp_global (#24)
  - [x] nxos_lldp_interfaces (#24)
  - [x] nxos_telemetry (#38)
  - [x] nxos_vlans (#38)

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

httpapi/nxos.py

**Comment by NilashishC** [comment]
@Qalthos - We also need to add nxos_bfd_global and nxos_telemetry to this list. Thanks!

**Comment by Qalthos** [comment]
@NilashishC Did you mean `nxos_bfd_interfaces`? `nxos_bfd_global` already has nxapi support.

**Comment by NilashishC** [comment]
> @NilashishC Did you mean `nxos_bfd_interfaces`? `nxos_bfd_global` already has nxapi support.

@Qalthos ah, right - bfd_interfaces.

**Comment by Qalthos** [comment]
Done!
