### ISSUE TITLE
Add new states to older Resource Modules

### ISSUE THREAD

**Issue by NilashishC** [ansible-collections/cisco.nxos#36]
##### SUMMARY
Add `gathered`, `rendered`, `parsed` support to the following RMs:
  - [x] nxos_hsrp_interfaces (#45)
  - [x] nxos_bfd_interfaces (#44)
  - [x] nxos_interfaces (#57)
  - [x] nxos_l2_interfaces (#37)
  - [x] nxos_l3_interfaces (#47)
  - [x] nxos_lacp (#39)
  - [x] nxos_lacp_interfaces (#41)
  - [x] nxos_lag_interfaces (#40)
  - [x] nxos_lldp_global (#42)
  - [x] nxos_vlans

##### ISSUE TYPE
- Feature Idea

**Comment by trishnaguha** [comment]
Please take care of adding fully qualified collection name in the examples for these modules in the same PRs as well.

**Comment by NilashishC** [comment]
Closing this since all the PRs are merged.
